Feature Check Runner
plx-pdg/plx pull request #50
Opened 2024-08-28 10:50 UTC by AndreCostaaa

Implements an Output Checker that can be constructed with a OutputCheck and the program output and will compare them using #49.

Since it's hard to image what other checkers will need, for now i'm creating an OutputChecker that will handle OutputChecks only. Depending on the future checker implementations, this can be refactored to share code between different checkers

Closes #37

2024-08-28 10:51 UTC, AndreCostaaa commented
Currently a draft as #49 waits reviews

Changes done to #49 will have to be merged here before reviewing this PR

2024-08-28 18:34 UTC, samuelroland commented
> Currently a draft as #49 waits reviews
> 
> Changes done to #49 will have to be merged here before reviewing this PR

@AndreCostaaa I merged #49, can you please fix the conflicts ? I tried but as some files were renamed this is getting a bit challenging. For ex. the `Diff.contains_differences` method is lost during merge, we have to copy paste. Same for lines like ` //TODO add timeout param here for very large files`

2024-08-28 18:40 UTC, AndreCostaaa commented
> > Currently a draft as #49 waits reviews
> > Changes done to #49 will have to be merged here before reviewing this PR
> 
> @AndreCostaaa I merged #49, can you please fix the conflicts ? I tried but as some files were renamed this is getting a bit challenging. For ex. the `Diff.contains_differences` method is lost during merge, we have to copy paste. Same for lines like ` //TODO add timeout param here for very large files`. I'm going to review this a few hours.

4a83934 does this

2024-08-28 23:13 UTC, samuelroland requested changes

2024-08-28 23:13 UTC, samuelroland commented on src/core/check/output_checker.rs
> +        let output = "hello ";
I guess this will not pass when tests are running as we discussed in the last call, even slight change should produce diff. But I suggest a similar behavior: we trim the end of each line before getting the diff. 

Any extra whitespace at the end is invisible and has no impact on human display, it should therefore not cause any diff by default (in Delibay, any solution is trimmed for the same reasons). The extra spaces at the end can come from a slight mistake in solution code, in given expected output or in student's answer.

So you can augment the test with multiple lines with or more whitespace characters, and make sure they don't cause any diff.

In addition, I like your idea of not allowing a whitespace at start, because it would shift the output to the right in console...

2024-08-29 09:50 UTC, AndreCostaaa commented on src/core/check/output_checker.rs
> +    core::diff::difference::Difference,
The merging went wrong and the file is not included i guess. My bad on that one

2024-08-29 09:50 UTC, AndreCostaaa commented on src/core/check/output_checker.rs
> +#[cfg(test)]
> The merging went wrong and the file is not included i guess. My bad on that one

Same issue here

2024-08-29 12:21 UTC, AndreCostaaa commented on src/core/check/output_checker.rs
> +
Good idea, done on d651b4b

2024-08-29 12:21 UTC, AndreCostaaa commented on src/core/check/output_checker.rs
> +    core::diff::difference::Difference,
Fixed on c0983f2

2024-08-29 12:26 UTC, AndreCostaaa commented on src/core/check/output_checker.rs
> +        }
I'm implementing it the "dumb" way first, there's certainly some refactoring to be done here when we implement the next checkers.
On one hand, the idea of getting the check is so we can easily add new data to the Check type that we can easily use to identify the test later
On the other hand, if we need to add other ways to identify the check we could also add them into the constructor

I'll let you decide and if you still want me to change it just let me know

2024-08-29 12:27 UTC, AndreCostaaa commented on src/core/check/output_checker.rs
> +#[cfg(test)]
Fixed on c0983f2

2024-08-29 12:27 UTC, AndreCostaaa commented on src/core/check/output_checker.rs
> +        let output = "hello ";
Done on 891d5a3

2024-08-30 17:27 UTC, samuelroland approved these changes
I improved the tests by making multiline comparisons in 49750a9f33d31d0075e9e3916a33d9dfe1ab360a and I think we are good enough for this module. Thanks a lot !

2024-08-30 17:27 UTC, samuelroland commented on src/core/check/output_checker.rs
> +        }
Okay, let's keep it with the "dumb" way first as is, thanks for the details.

2024-08-30 17:28 UTC, merged