Feat directory watcher
plx-pdg/plx pull request #64
Opened 2024-08-30 08:47 UTC by kevinAuberson

2024-08-30 09:17 UTC, AndreCostaaa requested changes

2024-08-30 09:17 UTC, AndreCostaaa commented on src/core/watcher/watcher.rs
> +        debouncer.watcher().watch(&self.exo.dir_path, RecursiveMode::Recursive).unwrap();
No reason to unwrap. If there's an error here there's no point in crashing the app

I don't think we should use recursive mode here

2024-08-30 09:17 UTC, AndreCostaaa commented on src/core/watcher/watcher.rs
> +    pub fn run(&self, tx: Sender<Event>){
you can move self here, avoiding the allowed extensions clone on the line below

```pub fn run(self, tx: Sender<Event>)```
instead of
```pub fn run(&self, tx: Sender<Event>)```

2024-08-30 09:17 UTC, AndreCostaaa commented on src/core/watcher/watcher.rs
> +    exo: Exo,
As we discussed, the file watcher can just take the files to watch, no need to have access to the exercise directly

2024-08-30 09:17 UTC, AndreCostaaa commented on src/core/watcher/watcher.rs
> +                return allowed_extensions.contains(&ext_str.to_lowercase());
Are we sure you want to force lower case here ?

I don't think we should make assumptions about the allowed extensions capitalization

2024-08-30 09:17 UTC, AndreCostaaa commented on src/core/watcher/watcher.rs
> +    fn test_run() {
This test should modify an existing file and check that only one event is received per change

The test name should also reflect this

2024-08-30 09:17 UTC, AndreCostaaa commented on src/core/work/worker.rs
> +                    watcher.run(self.tx);
Need to see if the directory watcher can be stopped or not

2024-08-30 13:36 UTC, kevinAuberson commented on src/models/exo.rs
> +    pub(crate) dir_path: PathBuf,
I don't know, how to add dir path as a dependency of watcher

2024-09-02 19:05 UTC, AndreCostaaa approved these changes

2024-09-02 19:07 UTC, merged